/** Formal academic disclaimer — shared by UI and documentation. */
export const ACADEMIC_DISCLAIMER_FULL =
  'This system is designed solely to provide academic risk indicators and predictive insights based on available academic data. It does not diagnose, determine, or identify the specific causes of a student’s academic difficulties. The results generated by the system are intended only as decision-support information and should not replace the professional judgment, guidance, assessment, or intervention of teachers, advisers, counselors, or other academic personnel.';

export const ACADEMIC_PREDICTION_REMINDER =
  'Predictions are intended for academic support purposes only.';

export const ACADEMIC_DISCLAIMER_TITLE = 'Academic use disclaimer';
